# *******************************
# *** Autor: Reymon Dev       ***# *** Datum: 8. Mai. 2026     ***
# *** Aktua: 8. Mai. 2026     ***
# *** Lizenz: AGPL-3-or-later ***
# *******************************

files_risk_microprice = files(
	'micro_price.c',                                                                                   
	'mid_price.c',
	'quote.c',
	'remaining_time.c',
	'reservation_price.c',
	'weighted_mid_price.c'
)