################################
### Author: Reymon Dev       ###
### Datum: 08 Mai 2026       ###
### Aktua: 15 August 2026    ###
### Lizenz: AGPL-3-or-later  ###
################################

############################
### Source File Variable ###
############################

source_files_exchange_kraken = []

######################
### Subdirectories ###
######################

subdir('client')
subdir('connection')
subdir('orders')