################################
### Author: Reymon Dev       ###
### Datum: 14. Mai. 2026     ###
### Aktua: 15. August. 2026  ###
### Lizenz: AGPL-3-or-later  ###
################################

#############
### Datei ###
#############

source_files_exchange_binance_client = files(
	'callback.c',
	'variables.c'
)

######################################
### Control Addcition Source Files ###
######################################

source_files_exchange_binance += source_files_exchange_binance_client